### ISSUE TITLE
Document `package.metadata.component` tables in `Cargo.toml`

### ISSUE THREAD

**Issue by vwkd** [bytecodealliance/cargo-component#194]
I'm looking for documentation on the `package.metadata.component` tables that can be specified in `Cargo.toml`.

Currently, `cargo component new --reactor foo` adds the following tables and keys.

```toml
[package.metadata.component]
package = "component:foo"

[package.metadata.component.target]
path = "wit"

[package.metadata.component.dependencies]
```

[cargo-component-bindings](https://docs.rs/cargo-component-bindings/latest/cargo_component_bindings/macro.generate.html#settings-1) also documents the [package.metadata.component.bindings] table.

Glancing through the [code](https://github.com/bytecodealliance/cargo-component/blob/8cfa63f72dc177916d226157ac4247709ee2b19e/src/metadata.rs#L267) suggests there are more tables.

```toml
[package.metadata.package]

[package.metadata.component.adapter]

[package.metadata.component.registries]
```

Can this be comprehensively documented somewhere?
