### ISSUE TITLE
adapter module does not have export `sock_getaddrinfo`

### ISSUE THREAD

**Issue by JMLX42** [bytecodealliance/cargo-component#217]
Hello,

I am trying to build an e-mail component that exports a function that can send an e-mail using MailGun.

Here is my `Cargo.toml`:

```toml
[package]
name = "email"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-component-bindings = "0.6.0"
mailgun-rs = { path = "./mailgun-rs", default-features = false }
tokio = { version = "1.35.1", features = ["rt"] }
wit-bindgen = "0.16.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:email"

[package.metadata.component.dependencies]
```

Here is the `mailgun-rs/Cargo.toml`:

```toml
[package]
name = "mailgun-rs"
version = "0.1.10"
authors = ["Dongri Jin <dongrify@gmail.com>"]
description = "An unofficial client library for the Mailgun API"
edition = "2018"
repository = "https://github.com/dongri/mailgun-rs"
license = "MIT"
keywords = ["email", "mailgun"]
documentation = "https://docs.rs/mailgun-rs"
readme = "README.md"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
typed-builder = "0.15.2"

[target.'cfg(not(target_os = "wasi"))'.dependencies]
reqwest = { version = "0.11.18", features = ["json"] }

[target.'wasm32-wasi'.dependencies]
reqwest_wasi = { version = "0.11.16", features = ["json"] }

[features]
default = ["blocking"]
blocking = ["reqwest/blocking"]
```

When I try to build this component with `cargo component build --release` I get the following error:

```
error: failed to reduce input adapter module to its minimal size

Caused by:
    adapter module does not have export `sock_getaddrinfo`

```

What am I doing wrong?
