### ISSUE TITLE
Error building when using cargo-component `bindings` instead of `wit-bindgen`

### ISSUE THREAD

**Issue by landonxjames** [bytecodealliance/cargo-component#264]
When building the following code with `cargo component build --release` it builds successfully with the `wit-bindgen` generated code, but fails using the `cargo-component` `bindings` code with:

```
error: module requires an import interface named `env`
```

I am using version 10.1:
```
$ cargo component --version                                           
cargo-component-component 0.10.1 (wasi:ab5a448)
```

Will try to split this out to a minimal repro in a bit, but at the moment it has some non-shareable code tied in. The relevant bits are below.

The code:
```rust
use serde_json;

// WORKS IF THIS IS USED INSTEAD
// wit_bindgen::generate!({
// world: "authoring-demo",
// additional_derives: [serde::Serialize, serde::Deserialize]});
// export!(Component);

// use exports::authoring_demo::component::clients::{
//     Guest as GuestClients, GuestAuthoringDemoClient,
// };
// use exports::authoring_demo::component::events::{
//     Foo, Guest as GuestEvents, GuestAuthoringDemoEvent,
// };

// FAILS error: module requires an import interface named `env`
#[allow(warnings)]
mod bindings;
bindings::export!(Component with_types_in bindings);

use bindings::exports::authoring_demo::component::clients::{
    Guest as GuestClients, GuestAuthoringDemoClient,
};
use bindings::exports::authoring_demo::component::events::{
    Foo, Guest as GuestEvents, GuestAuthoringDemoEvent,
};

//Impl the traits from your .wit file on these structs
struct Component;
struct AuthoringDemoClient;
struct AuthoringDemoEvent;

impl GuestClients for Component {
    type AuthoringDemoClient = AuthoringDemoClient;
}

impl GuestEvents for Component {
    type AuthoringDemoEvent = AuthoringDemoEvent;
}

impl GuestAuthoringDemoClient for AuthoringDemoClient {
    fn hello_world(&self) -> String {
        return "Hello World".to_string();
    }

    fn new() -> Self {
        AuthoringDemoClient
    }
}

impl GuestAuthoringDemoEvent for AuthoringDemoEvent {
    fn parse(&self, input: String) -> Result<Foo, String> {
        let parsed_val: Foo = serde_json::from_str(&input).map_err(|err| err.to_string())?;
        Ok(parsed_val)
    }

    fn new() -> Self {
        AuthoringDemoEvent
    }
}
```

The wit:
```wit
package authoring-demo:component;

interface clients { 

  resource authoring-demo-client {
    constructor();
    hello-world: func() -> string;
  }

}

interface events { 

  record foo {
    bar: string,
  }

  resource authoring-demo-event {
    constructor();
    parse: func(input: string) -> result<foo, string>;
  }

  
}

world authoring-demo { 
  export clients;
  export events;
}

```

The Cargo.toml

```toml
[package]
name = "authoring_demo"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen =  "0.21.0"
serde = {version = "1.0.193", features = ["derive"]}
serde_json = "1.0.108"
wit-bindgen-rt = "0.22.0"

# metadata used by cargo-component to identify which wit world to embed in the binary
[package.metadata.component]
package = "authoring-demo:component"

[package.metadata.component.bindings]
derives = ["serde::Serialize", "serde::Deserialize"]
```
