### ISSUE TITLE
Build fails with 'failed to create a target world for package ...'

### ISSUE THREAD

**Issue by denniskawurek** [bytecodealliance/cargo-component#279]
Hi,

I tried to follow the component-model example from [the tutorial by bytecodealliance](https://component-model.bytecodealliance.org/language-support/rust.html#importing-an-interface-into-a-command-component) with a slightly different service.

I created one component `stringlength` which is used by `app`.

When I run `cargo component build` in `app` I get a build error:

```
Caused by:
    0: failed to merge local target `/home/dennis/code/rust/wasm-components-sample/app/wit`
    1: package not found
            --> /home/dennis/code/rust/wasm-components-sample/app/wit/world.wit:4:12
             |
           4 |     import dkwr:stringlength/len@0.1.0;
             |            ^----------------
```

`stringlength` builds without any issues.

## Full code example (repo)

I've uploaded a full code example [here](https://github.com/denniskawurek/wasm-components-sample/).
Otherwise you can check the next paragraphs for the `wit` and `Cargo.toml` files.

## `wit` files and `Cargo.toml`

`stringlength.wit`:

```wit
package dkwr:stringlength@0.1.0;

interface len {
    len: func(s: string) -> u32;
}

world string-operations {
    export len;
}
```

`Cargo.toml` of `stringlength`:

```toml
[package]
name = "string_length"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-rt = { version = "0.24.0", features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "dkwr:string-operations"

[package.metadata.component.target]
path = "wit"
world = "string-operations"
```

`app.wit`

```wit
package dkwr:app@0.1.0;

world app {
    import dkwr:stringlength/len@0.1.0;
}
```

`Cargo.toml` of `app`:

```toml
[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-rt = { version = "0.24.0", features = ["bitflags"] }

[package.metadata.component]
package = "component:app"

[package.metadata.component.target]
path = "wit"

[package.metadata.component.dependencies]
"dkwr:stringlength" = { path = "../string_length/wit" }

```

What am I doing wrong? Thanks for your help!
