### ISSUE TITLE
Redesign `Cargo.toml` format

### ISSUE THREAD

**Issue by peterhuene** [bytecodealliance/cargo-component#28]
Currently, we mix exported and imported interfaces in the dependencies section and that can be quite confusing.

Originally it was intended that the `[package.metadata.component.dependencies]` section would be 1:1 with the normal `[dependencies]` section.

But having to mark some of the entries as `export = true` is clumsy; it's additionally clumsy to treat the default exported interface as the exported interface without a version.

Instead, I propose we change the format to be:

```toml
[package.metadata.component]
# Specifies the name of an export interface to export directly from the component
default = "interface"

[package.metadata.component.imports]
foo = "foo.wit"

[package.metadata.component.exports]
interface = "interface.wit"
bar = "bar.wit"
```

For now I also propose we remove the `version` field since it's currently unused and just use paths to the interface files to make thing cleaner.
