### ISSUE TITLE
`cargo component` does not obey `.cargo/config.toml`

### ISSUE THREAD

**Issue by oovm** [bytecodealliance/cargo-component#364]
I use `.cargo/config.toml` to control the compilation of workspace.

```toml
# .cargo/config.toml
[build]
target = "wasm32-wasip2"
```

But `cargo component build` still generates `wasm32-wasip1`

```yaml
cargo-component-component 0.19.0
```
