### ISSUE TITLE
How to specify the package namespace for local target dependencies

### ISSUE THREAD

**Issue by Iceber** [bytecodealliance/cargo-component#87]
My wit documentation references  the interface of a local dependency package, but `[package.metadata.component.target.dependencies]` requires that the package namespace must be specified
```bash
$ cargo component build
error: expected package identifier with format `<namespace>:<name>`
in `target.dependencies`
```

*wit dir*:
```bash
$  tree wit
wit
├── component.wit
└── deps
    └── test
        └── types.wit
```

*wit/component.wit*:
```wit
package component:hello-world

world command-adapter {
    import test: test.types

    export run: func() -> result
}
```

*Cargo.toml*:
```toml
[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wit-bindgen = { version = "0.6.0", default_features = false }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:hello-world"

[package.metadata.component.target]
path = "wit"

[package.metadata.component.target.dependencies]
"test" = { path = "wit/deps/test" }
```

**What should I set the namespace for local dependencies to?**

**If I specify a namespace at random, it raises a new error**
```
[package.metadata.component.target.dependencies]
"component:test" = { path = "wit/deps/test/" }
```
```bash
$ cargo component build
error: failed to read content of dependency `component:test` at path `/wasm/hello-world/wit/deps/test/`

Caused by:
  Is a directory (os error 21)
```
